name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
            name: irizzant/bitwarden-cli
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}